Pixelpro\miCMSBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: Pixelpro\miCMSBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '35'
        password:
            type: string
            length: '80'
    lifecycleCallbacks: {  }
